#!/usr/bin/Rscript

args <- commandArgs(trailingOnly = TRUE) 
lines <- readLines(args[1]) 

if (length(args) < 2) { 
	out.prefix = sub("^(.*).M-bias.txt", "\\1", basename(args[1]))
} else { 
	out.prefix = args[2] 
} 

startln.CpG = vector() 
read.len = 0 
read.len.2 = 0 

for (i in 1:length(lines)) { 
	if (length(grep("^CpG context",lines[i])) == 1) { 
		startln.CpG[length(startln.CpG)+1] = i + 3 
	}
	if (nchar(lines[i]) == 0) {
		if (length(startln.CpG) > 0 && read.len < 1) {
			read.len = i - startln.CpG[1] 
		}
		else if (length(startln.CpG)==2 && read.len.2 < 1) { 
		    read.len.2 = i - startln.CpG[2]
		}
	}
}

do.plot <- function(lines, name, prefix) { 
	table <- read.table(textConnection(paste(lines, collapse='\n'))) 
	table <- table[,c(1,4,5)] 
	options(scipen=10) 
	png(paste(prefix, "M-bias", "png", sep="."), width=600, height=500) 
	par(mar = c(5,5,2,5)) 
	#plot(table[,1], table[,2], xaxt="n", xlab="Read position", ylab="% methylation", ylim = c(0,min(max(table[,2])*1.1,100)), type='o', pch=19, cex=1.3)
	plot(table[,1], table[,2], xaxt="n", xlab="Read position", ylab="% methylation", ylim = c(0,100), type='o', pch=19, cex=1.3)
	axis(side=1, at=seq(1, length(table[,1]), by=5)) 
	par(new=T) 
	plot(table[,1], table[,3], axes=F, col="#FF000060", xlab=NA, ylab=NA, ylim=c(0,max(table[,3])*1.01), type='o', pch=19, cex=1.3) 
	axis(side=4, col = "red") 
	mtext(side = 4, line = 3, "Coverage") 
	title(name) 
	dev.off() 
} 

if (length(startln.CpG) == 1) { 
	do.plot(lines[startln.CpG:(startln.CpG+read.len-1)], "M-bias plot", out.prefix) 
} else if (length(startln.CpG) == 2) { 
	do.plot(lines[startln.CpG[1]:(startln.CpG[1]+read.len-1)], "M-bias plot (read 1)", paste(out.prefix,"read_1",sep=".")) 
	do.plot(lines[startln.CpG[2]:(startln.CpG[2]+read.len.2-1)], "M-bias plot (read 2)", paste(out.prefix,"read_2",sep=".")) 
} 

 
