#!/bin/bash
methyf="$1"
bedf="$2"
CAT=$([[ "$methyf" == *.gz ]] && echo "zcat" || echo "cat")

#                   duplicate position field to make BED          intersect with given BED file          remove dup pos
$CAT "$methyf" | sed 's/\(^[^\t]\+\t\)\([0-9]\+\t\)/\1\2\2/' | bedtools intersect -a - -b "$bedf" -u | cut -f3 --complement
